#!/bin/bash


# install packages
sudo apt install -y \
    nodejs npm ripgrep libssl-dev zlib1g-dev libbz2-dev libreadline-dev \
    libsqlite3-dev wget curl llvm libncursesw5-dev xz-utils tk-dev unzip \
    libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev zsh build-essential \
    tree xsel

# moving dotfiles
cp "$HOME/projects/wsl/dotfiles/.zshrc" ~/.zshrc
cp "$HOME/projects/wsl/dotfiles/.p10k.zsh" ~/.p10k.zsh

# install from source or prebuild binaries
"$HOME/projects/wsl/scripts/install-fzf"
"$HOME/projects/wsl/scripts/install-nvim"
"$HOME/projects/wsl/scripts/install-python"

# setup git
git config --global user.name "Towelie"
git config --global user.email "marcelmaier1996@outlook.de"
git config --global init.defaultBranch "main"
git config --global pull.rebase false
git config --global core.editor "nvim"

# change shell to zsh
chsh $USER -s /bin/zsh
exec zsh
