#!/bin/bash

# install packages
sudo apt install -y \
  zsh
  build-essential

# symlink dotfiles
# ln -s org link
cp dotfiles/.zshrc ~/.zshrc
cp dotfiles/.p10k.zsh ~/.p10k.zsh

# install from source or prebuild binaries
# fzf  ./scripts/install-fzf
./scripts/install-nvim

# setup git
git config --global user.name "Towelie"
git config --global user.email "marcelmaier1996@outlook.de"
git config --global init.defaultBranch "main"
git config --global pull.rebase false
git config --global core.editor "nvim"

# change shell to zsh
chsh $USER -s /bin/zsh
exec zsh
