vim.keymap.set('n', '<Esc>', '<cmd>nohlsearch<CR>')
vim.keymap.set('n', '<leader>dk', vim.diagnostic.goto_prev, { desc = '[D]iagnositcs Up' })
vim.keymap.set('n', '<leader>dj', vim.diagnostic.goto_next, { desc = '[D]iagnositcs Down' })
vim.keymap.set('n', '<leader>df', vim.diagnostic.open_float, { desc = '[D]iagnositcs Float' })
vim.keymap.set('n', '<leader>dl', vim.diagnostic.setloclist, { desc = '[D]iagnositcs List' })
vim.keymap.set('n', '<C-h>', '<C-w><C-h>', { desc = 'Left Window' })
vim.keymap.set('n', '<C-l>', '<C-w><C-l>', { desc = 'Right Window' })
vim.keymap.set('n', '<C-j>', '<C-w><C-j>', { desc = 'Down Window' })
vim.keymap.set('n', '<C-k>', '<C-w><C-k>', { desc = 'Up Window' })
