#!/bin/bash

# clone repo
gh repo clone filemanager ~/projects/filemanager/

# cd into folder
cd ~/projects/filemanager/

# install dependencies
pipenv install

# activate for shell
pipenv shell

# install build dependency
pip install pyinstaller

# build binary
pyinstaller --onefile fm.py

# cd out of installation folder
cd
