#!/bin/bash

# download latest binary tar ball
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz

# delete old nvim folder
sudo rm -rf /opt/nvim-linux64

# unpack tar ball
sudo tar -C /opt -xzf nvim-linux64.tar.gz

# remove tar ball
rm nvim-linux64.tar.gz

# move personal nvim configuration
# cp -p -r ~/projects/wsl/config/nvim ~/.config
