#!/bin/bash

# clone source
gh repo clone neovim/neovim ~/projects/nvim

# compile source
make -c ~/projects/nvim CMAKE_BUILD_TYPE=RelWithDebInfo

# move personal nvim configuration
cp -p -r ~/projects/wsl/config/nvim ~/.config
