#!/bin/bash

# clone repo
gh repo clone todos ~/projects/todos/

# cd into folder
cd ~/projects/todos/

# install dependencies
pipenv install

# activate for shell
pipenv shell

# install build dependency
pip install pyinstaller

# build binary
pyinstaller --onefile todos.py

# cd out of installation folder
cd
