#!/bin/bash

# clone repo
gh repo clone filemanager ~/projects/filemanager/

# cd into folder
cd ~/projects/filemanager/

# install dependencies
pyenv install -y

# activate for shell
pyenv shell

# install build dependency
pip install pyinstaller

# build binary
pyinstaller --onefile fm.py

# cd out of installation folder
cd
