#!/bin/bash

# clone repo
gh repo clone todos ~/projects/todos/

# cd into folder
cd ~/projects/todos/

# install dependencies
pipenv install

# activate for shell
pipenv run build

# cd out of installation folder
cd
