#!/bin/bash

# clone repo
gh repo clone filemanager ~/projects/filemanager/

# cd into folder
cd ~/projects/filemanager/

# install dependencies
pipenv install

# run build in a subshell with active environment
pipenv run pyinstaller --onefile fm.py

# cd out of installation folder
cd
