#!/bin/bash

# download latest binary
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz

# unpack tar ball
sudo tar -C /opt -xzf nvim-linux64.tar.gz

# remove tar ball
rm nvim-linux64.tar.gz

# move configuration
cp -p -r ~/projects/wsl/config/nvim ~/.config
